# -*- coding: utf-8 -*-
"""Demo T-I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBValbrfhbnadEP6JVJPlyfLnFutjjEQ
"""

!pip install diffusers transformers accelerate torch safetensors

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

prompt = "Taj Mahal"
image = pipe(prompt).images[0]
#image.save("pixelmind_demo.png")

image.save("pixelmind_demo.png")
import matplotlib.pyplot as plt
plt.imshow(image)
plt.axis('off')
plt.show()

